In [1]:
import pandas as pd 
import matplotlib.pyplot as ply
import numpy as np
import seaborn as sns
import datetime

In [3]:
df = pd.read_csv(r'C:\Users\user\Desktop\git 23\real_estate_15000_rows.csv')

In [4]:
df

,Year,Region,Country,City,Start_Date,End_Date,Stay_Days,Avg_Rent,Max_Rent,Min_Rent,Days_To_Rent,Area_sqm,Daily_Rent,Rental_Income,Avg_Stay_Days,Max_Stay_Days,Min_Stay_Days
0,2022,Asia,Japan,Delhi,2022-06-20,2022-07-22,32,1398,1763,1099,12,147,46.60,44736,30.379267,60,1
1,2021,Asia,India,Berlin,2021-03-23,2021-05-10,48,1444,1754,1227,26,23,48.13,69312,30.379267,60,1
2,2026,Europe,Germany,Berlin,2026-05-20,2026-07-08,49,827,2020,540,9,136,27.57,40523,30.379267,60,1
3,2026,Europe,France,Munich,2026-08-27,2026-10-02,36,1785,2664,1649,5,61,59.50,64260,30.379267,60,1
4,2025,China,China,Berlin,2025-06-03,2025-06-04,1,833,1780,474,2,106,27.77,833,30.379267,60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,2026,US,USA,Paris,2026-05-19,2026-06-27,39,1570,2220,1407,9,29,52.33,61230,30.379267,60,1
14996,2026,US,USA,Sao Paulo,2026-04-18,2026-05-31,43,1987,2875,1839,3,134,66.23,85441,30.379267,60,1
14997,2024,Europe,Germany,Paris,2024-04-20,2024-05-02,12,1639,2360,1511,23,91,54.63,19668,30.379267,60,1
14998,2024,China,China,Beijing,2024-04-01,2024-04-21,20,1981,2619,1678,19,22,66.03,39620,30.379267,60,1
14999,2022,US,USA,Rome,2022-02-12,2022-02-22,10,1247,1650,947,1,68,41.57,12470,30.379267,60,1

In [6]:
df[['Country']]

       Country
0        Japan
1        India
2      Germany
3       France
4        China
...        ...
14995      USA
14996      USA
14997  Germany
14998    China
14999      USA

[15000 rows x 1 columns]